### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by DPUkyle** [linkedin/rest.li#106]
A handful of subprojects are missing test-scope guava dependency... unless I'm missing some sort of undocumented setup?

Steps to reproduce:
1. `git checkout ad74aa98da8a55ad9c339d0769a3e8fb495765af`
2. `./gradlew clean check`

Project soon fails with issues such as:
```
> Task :data:compileTestJava 
rest.li/data/src/test/java/com/linkedin/data/schema/TestDataSchema.java:19: error: package com.google.common.collect does not exist
import com.google.common.collect.Lists;
```
My environment:
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_172 (Oracle Corporation 25.172-b11)
OS:           Linux 3.10.0-514.36.5.el7.x86_64 amd64
```

**Comment by evanw555** [comment]
Hi @DPUkyle, thanks for pointing this out and apologies for the seriously delayed response. We looked into this more and determined that we couldn't add the Guava dependencies back because we're trying to remove this dependency altogether. This is because it causes conflicts with certain other projects internally at LinkedIn that use both Rest.li and Guava. The solution we ended up going with was to simply remove usages of Guava in the modules that were failing to build. You can see the commit here:

https://github.com/linkedin/rest.li/commit/c1580d8c93d7f929e3cfe7f2fa3cce49bdb44fdb
