### ISSUE TITLE
`isAvroUnionMode` validation fails for all but first union member type

### ISSUE THREAD

**Issue by jpbetz** [linkedin/rest.li#53]
How to reproduce:

Set `isAvroUnionMode` to true on a validator.  Create a union for a few types, e.g.: `[ "Foo", "Bar" ]`.

Validating data for the `Foo` case passes.
Validating data for the `Bar` case fails.

[Here's why](https://github.com/linkedin/rest.li/blob/master/data/src/main/java/com/linkedin/data/schema/validation/ValidateDataAgainstSchema.java#L378):

```
else if (_options.isAvroUnionMode())
      {
        // Avro union default value does not include member type discriminator
        List<DataSchema> memberTypes = schema.getTypes();
        if (memberTypes.isEmpty())
        {
          addMessage(element, "value %1$s is not valid for empty union", object.toString());
        }
        else
        {
          DataSchema memberSchema = memberTypes.get(0);
          assert(_recursive);
          validate(element, memberSchema, object);
        }
      }
```

What this does does is check that the union schema has a least one option.  If it does, it gets the **first** option type and validates the data against that.  It doesn't even check with the `DataElement` to see what union memberKey key to use, so obviously this will not work.

I don't need `isAvroUnionMode` personally. But given that it's deeply broken, I recommend either fixing it or removing it.

**Comment by jpbetz** [comment]
It looks like code here was written specifically to validate schema default values, but has somehow been misplaced and is now being use to validate data against schemas.

**Comment by jpbetz** [comment]
I've proposed a fix as part of #50

**Comment by sweeboonlim** [comment]
The comments on AvroUnionMode is incorrect. It is used to validate as you said default values of Avro schemas. For default values of unions, the discriminator is not present to prevent verbose syntax like

{ "type" : [ "int", null ], "default" : { "int" : 5 } }

Avro default value of union is always the 1st type.

{ "type" : [ "int", null ], "default" : 5 }

This is why it always uses the 1st type of the union and because they is no key in the data.

This applies transitively even to default values of embedded unions. You can see this in the test case for schema translator tests for array of unions. Otherwise array of union of "optional" int in Avro would be ugly like [ { "int" : 5 }, { "int" : 6 } ] instead of [ 5, 6 ].

The comments regarding how AvroUnionMode is supposed to operate is incorrect. It was based on my incorrect understanding of how Avro handles default values of unions. The fix would be to modify the comments to indicate the AvroUnionMode validates default values of an Avro schema. In this mode, an union data value's will always be validated against the 1st type of the union. 

The test cases are in TestSchemaTranslator.

**Comment by jpbetz** [comment]
Thanks Swee, That makes so much more sense.

I'll propose a corrected change shortly.
