### ISSUE TITLE
SSL supporting

### ISSUE THREAD

**Issue by loloMui** [linkedin/rest.li#82]
Hello Rest.li team,
Your product really amazing, but....
We are currently using the Netty server and we don't find a way to use SSL. 

We really hope that it possible...

Waiting to hear from you ASAP
Thank you very much!

Lolo

**Comment by ssheng** [comment]
@weizlot Thanks for your interest. We internally have support for SSL but never had a chance to open source the classes. I am planning to enhance r2-netty server side support to bring functionality on-par with the client, such as SSL, HTTP/2, streaming.

But this is going to take some time to do. If you have urgent request for SSL support on r2-netty server, feel free to submit a PR for your use case. Otherwise, we will add these support to open source in the next couple of months.

**Comment by weizlot** [comment]
@ssheng  thank you for your response!
It's a good news! I think SSL is a very important feature which can take the Restli open source a few step forward.

For our project, SSL is required, but because we are already built a huge server based on Restli, and currently we haven't time to change it - so our temporary plan is to use Restli only for internal services.

Thank you again - waiting for yours update.

We having anther issue with the rest.li client - I'll open a new ticket for that.

Lolo

**Comment by loloMui** [comment]
Hey @ssheng, is there any estimate when you are going to release the SSL support for open-source? 

Thank you

**Comment by dengpan-yin** [comment]
@loloMui 
I will work on this issue, and expecting to release around the end of January.  Thank you for your patience. 

Dengpan

**Comment by loloMui** [comment]
@dengpan-yin awesome! thank you!

**Comment by dengpan-yin** [comment]
@loloMui  We have released the code change for this issue. Please check the following commit and examples.  If you have any questions, please let me know. 

Commit: https://github.com/linkedin/rest.li/commit/d54148ac5f356697761c4ceeb8ac6f980df0a97c
Example:  https://github.com/linkedin/rest.li/commit/d54148ac5f356697761c4ceeb8ac6f980df0a97c#diff-ac79e42dbfec464104ef26ceff596f05R73

To enable netty https server, you can use this class: HttpNettyServerBuilder
Similar to netty https client, you should prepare a SSLContext and SSLParameters(optional),
then pass these two variables with the other necessary parameters to update HttpNettyServerBuilder. Something like:
`HttpNettyServer nettyServer = HttpNettyServerBuilder()
 .port(port)
 .filters(filters)
 .transportDispatcher(dispatcher)
 .sslContext(sslContext)
 .sslParameters(sslParameters)
 .build();`

Thanks
Dengpan

**Comment by loloMui** [comment]
Wow thank you so much @dengpan-yin! it is really good news!
