### ISSUE TITLE
Rest.li Client - issue with building a request

### ISSUE THREAD

**Issue by loloMui** [linkedin/rest.li#83]
Hi Rest.li team,
We trying to build 2 servers. One of them (Server A) need to send a request to the other (Server B).

This is our structure:
**root project: "apis"** 
- Contains the serves api (pdsc + the generated java class). for each server there is a separate module.
````
|- build.gradle
|- settings.gradle
|
|- serverA-api/build.gradle
|- serverA-api/src/main/pegasus/net/servername/api/*.pdsc
|- serverA-api/src/mainGeneratedDataTemplate/java/.../*.java
|
|- serverB-api/build.gradle
|- serverB-api/src/main/pegasus/net/servername/api/*.pdsc
|- serverB-api/src/mainGeneratedDataTemplate/java/.../*.java
````

**root project: "server-A"** 
- Contains the "serverA-api" as a library and Implemented the api use cases.

**root project: "server-B"** 
- Contains the "serverA-api" as a library - because we want to make a requests to server A.
- Contains the "serverB-api" as a library and implemented the api use cases.

------------------

While implementing the servers api use cases everything works well, but with implementing the rest client we got troubles...
We are a bit confused with how to make a restClient requests on our current structure from server A to server B.

do we have to create a request builder class? - if yes, how?
The docs for this part are a bit confusing, what is the "product_spec.json"?
https://github.com/linkedin/rest.li/wiki/Rest.li-User-Guide#depending-on-data-templates

## **BTW**, 
is the Web UI dead? it doesn't work - also the "restli-apihub-0.0.2.zip" download link broken. 
https://github.com/linkedin/rest.li-api-hub

Thank you

**Comment by loloMui** [comment]
@ssheng ?

**Comment by mchen07** [comment]
@loloMui, we are currently investigating the issue you reported, will get back to you on this shortly.

**Comment by saponniah** [comment]
Hi @loloMui 

Ideally both the 'api' and 'server' modules should be under the same project. Having these two modules under the same project is necessary to publish IDL files into the 'api' module whenever there is a change in resource implementation under the 'server' module. Since all the necessary artifacts for calling this resource is under the 'api' module, the clients can just depend on this module.

Based on my understanding of your use case, here is a suggested structure that will better fit your use case.

```
Root project for ResourceA
|_ 'api' module for ResourceA
|_ 'server' module for ResourceA

Project for ResourceB
|_ 'api' module for ResourceB
|_ 'server' module for ResourceB (with a dependency to ResourceB's api module)
```

> do we have to create a request builder class? - if yes, how?

Yes, once the IDL files have been published to the 'api' module rebuilding the 'api' module will generate the client builders. I'm having some trouble generating these client builders when I tried on the quickstart example locally. Most likely I have something wrong in my setup - I'll get back to you on this.

> The docs for this part are a bit confusing, what is the "product_spec.json"?

This is a LinkedIn specific dependency configuration file. I have updated this section in the documentation to refer to Gradle files.

**Comment by loloMui** [comment]
Thank you @saponniah and @mchen07 

We will try @saponniah 's suggestion by tomorrow.

do you have any idea about the Web UI? it seems to be dead, - also the "restli-apihub-0.0.2.zip" download link broken.
https://github.com/linkedin/rest.li-api-hub

**Comment by loloMui** [comment]
Actually I can't wait for tomorrow : )
Thank you @saponniah , using your suggested structure I succeed to generate the builders !! but only after I run manually the command:
```` gradle generate{sourceSet}GeneratedRestRestClient

**Comment by maximelamure** [comment]
@loloMui, we would love to know more about your use cases and see how we can help you. Would you be available to discuss? you can contact me at mlamure@linkedin.com

**Comment by saponniah** [comment]
@loloMui Great that helped. Yes, I should have mentioned the Gradle task name that can be used directly to build the client builders.

Regarding Rest.li API Hub, it is definitely under our radar but hasn't got the needed love due to other developments in the core rest.li project. For now, can you download the binary directly from here?

https://github.com/linkedin/rest.li-api-hub/raw/86b3f4008478e4b248113cbc39c4205e71beeed3/releases/apihub/restli-apihub-0.0.2.zip

As @maximelamure mentioned, feel free to reach out to him directly as we would like to hear more to understand and provide better suggestions for your use case.

**Comment by loloMui** [comment]
Thank you so much for your help @maximelamure  and @saponniah.
We are keep moving forward with the project and the Restli doing an amazing job so far.
Currently we are looking about a SSL solution, since the Open Source project doesn't has the support yet (as @ssheng  told us).

Is there any estimate when the SSL will be available for the open source ?

**Comment by mchen07** [comment]
As updated in https://github.com/linkedin/rest.li/issues/82, SSL support is already available for open source. I am closing this issue then.
